name = "strike/agent-vault"
version = "1.0.0"
compiler = "v1.1.7"
plutus = "v3"
license = "MIT"
description = "Secure Agent Vault smart contract for automated Strike Finance trading without private key exposure"

[repository]
user = "strike"
project = "agent-vault"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "v2.2.0"
source = "github"

[config]
