name = "mrstrike/simple-vault"
version = "0.0.0"
compiler = "v1.1.7"
plutus = "v3"
license = "Apache-2.0"
description = "Aiken contracts for project 'mrstrike/simple-vault'"

[repository]
user = "mrstrike"
project = "simple-vault"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "v2.2.0"
source = "github"

[config]
